### ISSUE TITLE
__main__.LiquiApiError: external service unavailable

### ISSUE THREAD

**Issue by Whitesttax** [banteg/liqui#3]
I'm sorry if this isn't something worth opening an issue, but I'm having this problem, like, a lot.
"__main__.LiquiApiError: external service unavailable"
Do you know what it is?

**Comment by banteg** [comment]
This is an exchange issue, not a problem with a library. You can catch it with a try-except block.

**Comment by Whitesttax** [comment]
I see, something like the error 503, maybe?
